// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2K6n5AUh7L0_41REzGOsMYVHSwq903-Q',
    appId: '1:741495920866:web:fe88cbd23317014410a6bb',
    messagingSenderId: '741495920866',
    projectId: 'compost-tcu468',
    authDomain: 'compost-tcu468.firebaseapp.com',
    storageBucket: 'compost-tcu468.appspot.com',
    measurementId: 'G-1P3WR8T3MX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbJm7H3XlneBtQmd2NZjmn_aPeJ8cV9vE',
    appId: '1:741495920866:android:4f88f8b1b3e70d0f10a6bb',
    messagingSenderId: '741495920866',
    projectId: 'compost-tcu468',
    storageBucket: 'compost-tcu468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNZC2pNlrP6aQafpi5kGu1kG8-ZylYH0k',
    appId: '1:741495920866:ios:7f3df147980aa6d310a6bb',
    messagingSenderId: '741495920866',
    projectId: 'compost-tcu468',
    storageBucket: 'compost-tcu468.appspot.com',
    iosClientId:
        '741495920866-mbunj99qjspoi7gulhggmskn9oi33jme.apps.googleusercontent.com',
    iosBundleId: 'com.example.compost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNZC2pNlrP6aQafpi5kGu1kG8-ZylYH0k',
    appId: '1:741495920866:ios:7f3df147980aa6d310a6bb',
    messagingSenderId: '741495920866',
    projectId: 'compost-tcu468',
    storageBucket: 'compost-tcu468.appspot.com',
    iosClientId:
        '741495920866-mbunj99qjspoi7gulhggmskn9oi33jme.apps.googleusercontent.com',
    iosBundleId: 'com.example.compost',
  );
}
